### PR TITLE
Rpg 3

### PR DESCRIPTION
**Pull request by JacobJ97**
Resolves issue #3 

Student Overview page.

### CODE REVIEW

**Comment by JacobJ97** [comment]
@lrobert142 @Tukeyan

**Comment by JacobJ97** [comment]
Some notes:
- Make sure that's there's a Student Overview page in your Wordpress Admin, and that the template has been switched to "student-overview."
- When logging in as a student for the first time, it automatically creates a new user which has a student role. This was to show that different users can see different data.

username: phpcreateduser
password: password

**Comment by lrobert142** [comment]
Cool, I'll pull this down and test later this week.

**Review by lrobert142 — APPROVED** [review]
Interesting use of wpdb, I would have assumed there would be wrappers for some of this higher level stuff... but if it works (and it does) then I'm happy to merge.

**Pull request merged**
